### ISSUE TITLE
When will infobip api start supporting python 3

### ISSUE THREAD

**Issue by shubh12et1062** [infobip/infobip-api-python-client#12]

**Comment by shubh12et1062** [comment]
No response

**Comment by kiselica-aldin** [comment]
Hi @shubh12et1062

as you might have noticed, we recently formed a DevRel initiative and all of the published API client libs are being released in a newer fashion one by one (Java and PHP already, C# in final polishing phase, Python in early configuration tweaking stage).

Apologies for making you wait, we are taking ownership of the libraries as we tackle them. 

Regarding Python, it is being configured and right after that polishing and release of the C# lib is done, the full focus of the team will be on polishing new major release of this library -> `v3.0.0` during this quarter.

We are trying to make it target versions `Python >= 3.6`.
