### ISSUE TITLE
How to send messages over Whatsapp channel through Omni api  via python3

### ISSUE THREAD

**Issue by shubh12et1062** [infobip/infobip-api-python-client#13]

**Comment by kiselica-aldin** [comment]
Hello @shubh12et1062  

I already introduced to you the idea of our library's new major release in general.
However, the first release will most probably NOT contain the Omni.

What I can offer as a short-term alternative would be triggering it directly through HTTP API.
If you check this API docs page for [this](https://www.infobip.com/docs/api#channels/omni-failover/send-omni-failover-message) endpoint, you will see how you can from within your service (without the client) trigger it by using the python example on the right-hand side. 

DISCLAIMER: the example actually contains several message types - none of them being WA, which means you will have to adjust the JSON string in the `payload` variable to suit your needs.

On the bright side, within `REQUEST BODY SCHEMA` you can easily find all the available WA-related fields which you might want to set there.

Hopefully, this will work for you until we provide what you need within the lib.

**Comment by ivan-letenko** [comment]
Hi,
Just for your information, we are going to include standalone WhatsApp API endpoints in the new library soon.
