### ISSUE TITLE
SMSTextualRequest package import issue

### ISSUE THREAD

**Issue by FaTal-error1** [infobip/infobip-api-python-client#14]
Unable to use the SMSTextualRequest object to send the SMS. I tried to import the package using all the following paths above but none of them worked.
from infobip_api_client.model.SmsAdvancedTextualRequest import SmsAdvancedTextualRequest
from infobip_api_client.model import SmsAdvancedTextualRequest
from infobip_api_client.model import *

**Comment by kiselica-aldin** [comment]
Hello @FaTal-error1 

have you maybe tried going with:
`from infobip_api_client.model.sms_advanced_textual_request import SmsAdvancedTextualRequest`

You see, when imported by default library name really is `infobip_api_client` and the models really are found within `model` directory. But if you closely check on the file names, the class `SmsAdvancedTextualRequest` is within `sms_advanced_textual_request.py` file.

Regarding the asterisk usage, this would be the alternative approach:
`from infobip_api_client.model.sms_advanced_textual_request import *` but I always recommend going with class direct class imports until it gets too messy to track, which should not be the case here. 😃

This should solve your issue, but if something still occurs ping us back (in this or new issue, depending on the cause).

**Comment by FaTal-error1** [comment]
Hello @kiselica-aldin,

Thank you for your reply, I appreciate your help.
