### ISSUE TITLE
# name 'SendSmsApi' is not defined

### ISSUE THREAD

**Issue by ayoubaayoub** [infobip/infobip-api-python-client#15]
Hello.
I get this error win I try to send an SMS 
`from infobip_api_client.api_client import ApiClient, Configuration
from infobip_api_client.model.sms_advanced_textual_request import *
from infobip_api_client.model.sms_textual_message import *
from infobip_api_client.model.sms_destination import *`
can someone help
Thanks.

**Comment by kiselica-aldin** [comment]
Hello @ayoubaayoub 

I see, the issue you are experiencing is similar to the #14 
If you browse through the dependency, you will see that `SmsTextualMessage` model is located within the `sms_textual_message.py` file.

In your attempt, you successfully directly imported `ApiClient` and `Configuration` models.
As well as all of the models included within the `sms_advanced_textual_request.py` file.
Hence to properly import `SmsTextualMessage`, you would have to import it separately as well:

You can do that by adding either:
`from infobip_api_client.model.sms_textual_message import SmsTextualMessage`
or alternatively, to import all models from that file:
`from infobip_api_client.model.sms_textual_message import *`

**Comment by kiselica-aldin** [comment]
Ah, now I see you completely changed the issue :)
Let me quickly read that again

**Comment by kiselica-aldin** [comment]
So, same as above...

If you browse through the dependency, you will see that `SendSmsApi` API class is located within the `send_sms_api.py` file.

Hence use either:
`from infobip_api_client.api.send_sms_api import SendSmsApi`

or with an asterisk:
`from infobip_api_client.api.send_sms_api import *`

**Comment by ayoubaayoub** [comment]
@kiselica-aldin  thank you very much :).
