### ISSUE TITLE
 AttributeError: module 'enum' has no attribute 'IntFlag' Python 3.6.2

### ISSUE THREAD

**Issue by folt** [infobip/infobip-api-python-client#7]
hi 
I run command `pip install infobip-api-python-client`
the command failed
error 

> Collecting infobip-api-python-client
>   Using cached https://files.pythonhosted.org/packages/d8/b6/6f975e3e795643dc86b4c19cc57f1acdc04bea35f9613ce93ce4244bb645/infobip-api-python-client-2.2.0.tar.gz
> Collecting enum (from infobip-api-python-client)
>   Using cached https://files.pythonhosted.org/packages/0c/4e/1ea357e7783c756bb579333c1e4a026fb331371ee771f616ffedc781e531/enum-0.4.6.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/Users/folt/Documents/Working/dev_messenger/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
>         import distutils.core
>       File "/Users/folt/Documents/Working/dev_messenger/venv/lib/python3.6/distutils/__init__.py", line 4, in <module>
>         import imp
>       File "/Users/folt/Documents/Working/dev_messenger/venv/lib/python3.6/imp.py", line 27, in <module>
>         import tokenize
>       File "/Users/folt/Documents/Working/dev_messenger/venv/lib/python3.6/tokenize.py", line 33, in <module>
>         import re
>       File "/Users/folt/Documents/Working/dev_messenger/venv/lib/python3.6/re.py", line 142, in <module>
>         class RegexFlag(enum.IntFlag):
>     AttributeError: module 'enum' has no attribute 'IntFlag'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j_/qkr9lhfd0g593b64465q50cr0000gn/T/pip-install-59o613b7/enum/

I use Python 3.6.2

**Comment by denis-cutic** [comment]
Hi,

currently, we support only python2 as listed in the supported languages section on [pypi](https://pypi.org/project/infobip-api-python-client/).
We will see to it that support for python3 gets added in the future.

Kind regards

**Comment by neoecos** [comment]
@denis-cutic hi man! This is taking too long, everybody is using python 3 now!

**Comment by hkozacinski** [comment]
Hi @neoecos!
We are in the process of making new libraries, including a new Python lib for Python 3. I realize the process is slow, but you can expect changes in the upcoming months.
Kind regards

**Comment by luistm** [comment]
Hi, 
Do you guys have some lib for python 3 already? I the there is a pull request pending for some time now. 

Thanks

**Comment by denis-cutic** [comment]
Hi,

as the code is automatically generated we are not accepting pull requests.
Also, we are not planning to upgrade the current Python library to support Python 3.

On the other hand we are working on providing OpenApi specifications for our APIs. This will allow you to generate libraries for various languages, including Python 3. 

For the time being I suggest either forking the repository or using one of the existing forks supporting Python 3.

Kind regards

**Comment by folt** [comment]
a separate library is a good solution

**Comment by z4id** [comment]
@hkozacinski , @denis-cutic 
Any update on this ?
Is Python 3 supported now ?
Or that OPEN API Specification document ready ?

**Comment by Gurpreet23-design** [comment]
i have a problem while running code on pycharm 
every code i try to run using pygame it throw me with an error module 'enum' has no attribute 'IntFlag'
i have also tried to uninstall enum 34 but it shows me this "Skipping enum34 as it is not installed." 
please help me with this i am using python 3.8 version

**Comment by Gurpreet23-design** [comment]
Traceback (most recent call last):
  File "C:/Users/DELL/Desktop/pyhton/OOPS/game.py", line 1, in <module>
    import pygame
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygame\__init__.py", line 202, in <module>
    import pygame.threads
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pygame\threads\__init__.py", line 15, in <module>
    import traceback, sys
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38-32\lib\traceback.py", line 5, in <module>
    import linecache
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38-32\lib\tokenize.py", line 32, in <module>
    import re
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python38-32\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by Gurpreet23-design** [comment]
please help

**Comment by shubh12et1062** [comment]
Any updates?

**Comment by folt** [comment]
I suggest making a fork

**Comment by ivan-letenko** [comment]
Hi! We are currently upgrading all our client libraries, next will be Python, it will be automatically generated and completely different from the current version.
You can expect this next month.
